# 第二次课作业

In [1]:
import numpy as np
from numpy import *

（1）创建一个1到10的数组，然后逆序输出。

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [5]:
a = np.arange(1,11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [6]:
a = np.ones(20)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
a = np.ones(20,dtype='int')
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
b = a.reshape(4,5)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
b.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

##### random生成0-1的随机数

In [15]:
a = np.random.random((3,3,3))
a

array([[[0.77376802, 0.63097401, 0.6665986 ],
        [0.29284957, 0.20524241, 0.58962782],
        [0.08435724, 0.56450489, 0.72404519]],

       [[0.27354985, 0.66864648, 0.46159808],
        [0.36557832, 0.36242973, 0.30128867],
        [0.73085546, 0.30347793, 0.99524701]],

       [[0.6067707 , 0.05153112, 0.96711137],
        [0.88947799, 0.05523131, 0.06011848],
        [0.24617877, 0.55016185, 0.80908052]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

#### randint生成整数随机数，可以设置范围[1,11)

In [22]:
a = np.random.randint(1,11,10)
a

array([ 2,  3,  6,  7,  8,  3,  3, 10,  1,  5])

In [24]:
a.sort()
a

array([ 1,  2,  3,  3,  3,  5,  6,  7,  8, 10])

In [25]:
a.max()

10

In [26]:
a.min()

1

In [27]:
a.sum()

48

In [28]:
a.var()

7.5600000000000005

In [29]:
a.mean()

4.8

（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [32]:
a = np.random.randint(1,11,10)
a

array([ 8,  9,  3,  7,  9, 10,  3,  2,  2,  1])

In [34]:
where(a%2==1)

(array([1, 2, 3, 4, 6, 9], dtype=int64),)

In [35]:
a[where(a%2==1)]

array([9, 3, 7, 9, 3, 1])

In [36]:
a[a%2==1]

array([9, 3, 7, 9, 3, 1])

In [37]:
a%2==1

array([False,  True,  True,  True,  True, False,  True, False, False,
        True])

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [40]:
a = np.linspace(0,100,21)
a

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [41]:
a.astype('int')

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [42]:
a = np.random.randint(1,11,10)
a

array([4, 8, 4, 6, 9, 4, 1, 6, 2, 1])

In [45]:
a[(a>3)&(a<8)]*= -1
a

array([-4,  8, -4, -6,  9, -4,  1, -6,  2,  1])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [46]:
a = [1,2,3,4,5]
b = np.zeros(9,dtype=int)
b[::2]=a
b

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [47]:
a = np.random.randint(1,10,(5,5))
a

array([[3, 8, 5, 1, 9],
       [5, 3, 2, 1, 6],
       [6, 3, 3, 5, 5],
       [6, 5, 7, 8, 6],
       [5, 9, 5, 6, 4]])

In [48]:
a[0]

array([3, 8, 5, 1, 9])

In [49]:
a[:,0]

array([3, 5, 6, 6, 5])

In [50]:
a[[1,0,2,3,4]]

array([[5, 3, 2, 1, 6],
       [3, 8, 5, 1, 9],
       [6, 3, 3, 5, 5],
       [6, 5, 7, 8, 6],
       [5, 9, 5, 6, 4]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

In [51]:
a = np.random.randint(1,10,(10,2))
x = a[:,0]
y = a[:,1]

In [52]:
r = np.sqrt(x**2+y**2)
r

array([ 9.48683298,  6.08276253,  6.40312424, 11.40175425, 10.63014581,
        9.21954446,  9.21954446,  9.48683298,  7.07106781,  2.23606798])

In [54]:
R = np.arctan(y/x)
R

array([0.32175055, 1.40564765, 0.89605538, 0.90975316, 0.71883   ,
       1.35212738, 0.86217005, 0.32175055, 0.14189705, 0.46364761])

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [55]:
a = np.ones(10,dtype=int)
a.fill(2)
a

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [56]:
a[4]=1
a

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

（12）创建一个长度为10的随机向量，并求其累计和。

In [60]:
a = np.random.randint(1,10,10)
a


array([6, 4, 6, 5, 9, 1, 7, 4, 1, 3])

In [61]:
np.cumsum(a)

array([ 6, 10, 16, 21, 30, 31, 38, 42, 43, 46], dtype=int32)

In [62]:
a.cumsum()

array([ 6, 10, 16, 21, 30, 31, 38, 42, 43, 46], dtype=int32)

（13）将数组中的所有奇数替换成-1。

In [63]:
a = np.random.randint(1,10,10)
a

array([8, 4, 6, 5, 4, 5, 3, 7, 9, 6])

In [64]:
a[a%2==1] = -1

In [65]:
a

array([ 8,  4,  6, -1,  4, -1, -1, -1, -1,  6])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [66]:
a = np.random.randint(1,10,(4,3))
b = np.random.randint(1,10,(4,3))
a

array([[6, 7, 6],
       [8, 1, 2],
       [4, 3, 6],
       [6, 9, 2]])

In [67]:
np.vstack((a,b))#垂直堆叠

array([[6, 7, 6],
       [8, 1, 2],
       [4, 3, 6],
       [6, 9, 2],
       [8, 9, 1],
       [2, 7, 6],
       [2, 8, 8],
       [2, 7, 1]])

In [68]:
np.hstack((a,b))#横向堆叠

array([[6, 7, 6, 8, 9, 1],
       [8, 1, 2, 2, 7, 6],
       [4, 3, 6, 2, 8, 8],
       [6, 9, 2, 2, 7, 1]])

In [69]:
np.dstack((a,b))#三维堆叠

array([[[6, 8],
        [7, 9],
        [6, 1]],

       [[8, 2],
        [1, 7],
        [2, 6]],

       [[4, 2],
        [3, 8],
        [6, 8]],

       [[6, 2],
        [9, 7],
        [2, 1]]])

（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [70]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a-b
c

array([-6,  0, -7,  0, -4,  0, -6,  0, -4, -2])

In [71]:
where(c==0)

(array([1, 3, 5, 7], dtype=int64),)

In [72]:
a[c==0]

array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [73]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
a[(a>5)&(a<10)]

array([7, 7, 9, 9, 8])